In [1]:
using LowLevelFEM

In [2]:
openGeometry("truss2D.geo")

#openPreProcessor(openGL=true)

Info    : Clearing all models and views...
Info    : Done clearing all models and views
Info    : Reading 'truss2D.geo'...
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 60%] Meshing curve 2 (Line)
Info    : Done meshing 1D (Wall 0.000344011s, CPU 0.000299s)
Info    : 3 nodes 5 elements
Info    : Done reading 'truss2D.geo'


In [3]:
mat = Material("rod", E=1, A=1)
Pu = Problem([mat], type=:VectorField, dim=2, field=:u, rhs_field=:f)

Problem("truss2D", :VectorField, 2, 2, Material[Material("rod", :Hooke, 1.0, 0.3, 0.5769230769230768, 0.3846153846153846, 0.8333333333333333, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 3, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f)

In [4]:
A = mat.A
E = mat.E

1.0

In [5]:
t = tangentVector(Pu, "rod")
showElementResults(t)
t1 = [t[1]; t[2]; 0; 0;;]

4×1 Matrix{Any}:
  ScalarField([[0.8944271909999159; 0.8944271909999159;;], [1.0; 1.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5], 1, :scalar, Problem("truss2D", :VectorField, 2, 2, Material[Material("rod", :Hooke, 1.0, 0.3, 0.5769230769230768, 0.3846153846153846, 0.8333333333333333, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 3, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f))
  ScalarField([[0.4472135954999579; 0.4472135954999579;;], [0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5], 1, :scalar, Problem("truss2D", :VectorField, 2, 2, Material[Material("rod", :Hooke, 1.0, 0.3, 0.5769230769230768, 0.3846153846153846, 0.8333333333333333, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 3, LowLevelFEM.Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f))
 0
 0

In [6]:
t1 * t1'

4×4 Matrix{Any}:
 ScalarField([[0.8; 0.8;;], [1.0; 1.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5], 1, :scalar, Problem("truss2D", :VectorField, 2, 2, Material[Material("rod", :Hooke, 1.0, 0.3, 0.576923, 0.384615, 0.833333, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 3, Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f))  …   ScalarField([[0.0; 0.0;;], [0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5], 1, :scalar, Problem("truss2D", :VectorField, 2, 2, Material[Material("rod", :Hooke, 1.0, 0.3, 0.576923, 0.384615, 0.833333, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 3, Geometry("", "", 0, 0, nothing, nothing, nothing, nothing), :u, :f))
 ScalarField([[0.4; 0.4;;], [0.0; 0.0;;]], Matrix{Float64}(undef, 0, 0), [0.0], [4, 5], 1, :scalar, Problem("truss2D", :VectorField, 2, 2, Material[Material("rod", :Hooke, 1.0, 0.3, 0.576923, 0.384615, 0.833333, 7.85e-9, 45.0, 4.2e8, 1.2e-5, 1.0e-7, 0.1, 1.0)], 1.0, 3, Geometry("", "", 0, 0, nothing,

In [7]:
K = ∫(AxialGrad(Pu) ⋅ (A * E) ⋅ AxialGrad(Pu))
K[:, :]

6×6 SparseArrays.SparseMatrixCSC{Float64, Int64} with 19 stored entries:
  0.357771   0.178885     ⋅    ⋅   -0.357771  -0.178885
  0.178885   0.0894427    ⋅    ⋅   -0.178885  -0.0894427
   ⋅          ⋅          0.5   ⋅   -0.5         ⋅ 
   ⋅          ⋅           ⋅    ⋅     ⋅          ⋅ 
 -0.357771  -0.178885   -0.5   ⋅    0.857771   0.178885
 -0.178885  -0.0894427    ⋅    ⋅    0.178885   0.0894427

In [8]:
#f0 = ∫(Pu ⋅ [1,1])

In [9]:
fR = ∫(Pu ⋅ [0, -1], Γ="3")

nodal VectorField
[0.0; 0.0; … ; 0.0; -1.0;;]

In [10]:
supp1 = BoundaryCondition("1", ux=0, uy=0)
supp2 = BoundaryCondition("2", ux=0, uy=0)

BoundaryCondition("2", nothing, Dict{Symbol, Union{Function, Number, ScalarField}}(:uy => 0, :ux => 0))

In [11]:
u = solveField(K, fR, support=[supp1, supp2])
u.a

6×1 Matrix{Float64}:
   0.0
   0.0
   0.0
   0.0
   3.9999999999999996
 -19.180339887498945

In [12]:
t = tangentVector(Pu, "rod")

elementwise VectorField
[[0.8944271909999159; 0.4472135954999579; … ; 0.4472135954999579; 0.0;;], [1.0; 0.0; … ; 0.0; 0.0;;]]

In [13]:
N = A * E * (expandTo3D(u) ⋅ t)

elementwise ScalarField
[[0.0; -4.999999999999998;;], [0.0; 3.9999999999999996;;]]

In [14]:
u0 = showDoFResults(u)
#N0 = showElementResults(N)

1

In [15]:
#plotOnPath("rod", u0)
#plotOnPath("rod", N0)

In [16]:
openPostProcessor()

-------------------------------------------------------
Version       : 4.15.2-git
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 19700101
Build host    : amdci7.julia.csail.mit.edu
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blossom Cairo DIntegration Dlopen DomHex Eigen[contrib] Fltk GMP Gmm[contrib] Hxt Jpeg Kbipack LinuxJoystick MathEx[contrib] Mesh Metis[contrib] Mmg Mpeg Netgen Nii2mesh ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR TinyXML2[contrib] Untangle Voro++[contrib] WinslowUntangler Zlib tinyobjloader
FLTK version  : 1.3.8
OCC version   : 7.9.2
Packaged by   : root
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


XOpenIM() failed
Fontconfig warning: using without calling FcInit()


In [17]:
expandTo3D(nodesToElements(u)) ⋅ t

elementwise ScalarField
[[0.0; -4.999999999999998;;], [0.0; 3.9999999999999996;;]]

In [18]:
n = 4
A = zeros(n, n)
K = ∫(Grad(Pu) ⋅ A ⋅ Grad(Pu))
K[:, :]

6×6 SparseArrays.SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 