In [1]:
import gmsh
gmsh.initialize()

In [2]:
# Geometria megrajzolása
gmsh.model.add("rectangle")

p1 = gmsh.model.occ.addPoint(0, 0, 0)
p2 = gmsh.model.occ.addPoint(2, 0, 0)
p3 = gmsh.model.occ.addPoint(2, 1, 0)
p4 = gmsh.model.occ.addPoint(0, 1, 0)

l1 = gmsh.model.occ.addLine(p1, p2)
l2 = gmsh.model.occ.addLine(p2, p3)
l3 = gmsh.model.occ.addLine(p3, p4)
l4 = gmsh.model.occ.addLine(p4, p1)

cl1 = gmsh.model.occ.addCurveLoop([l1, l2, l3, l4])

sf1 = gmsh.model.occ.addPlaneSurface([cl1])

gmsh.model.occ.synchronize()

In [3]:
# Végeselemes felosztás elvégzése

# lekérjük az összes csomópontot
all = gmsh.model.getEntities(0)
# megadjuk, hogy a csomóponthoz rendelt eleméret mekkora legyen
gmsh.model.mesh.setSize(all, 1)
# kiválasztjuk a 8-as számú hálózó algoritmust a 2D-s sf1 felülethez
gmsh.model.mesh.setAlgorithm(2, sf1, 8)
# legeneráljuk a hálót a felület kontúrjához (1D-s)
gmsh.model.mesh.generate(1)
# legeneráljuk a hálót a felülethez (2D-s)
gmsh.model.mesh.generate(2)
# a legenerált háromszög elemeket négyszög elemekké alakítjuk
gmsh.model.mesh.recombine()

gmsh.model.mesh.setOrder(2)

Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 30%] Meshing curve 2 (Line)
Info    : [ 50%] Meshing curve 3 (Line)
Info    : [ 80%] Meshing curve 4 (Line)
Info    : Done meshing 1D (Wall 0.000428044s, CPU 0.000403s)
Info    : 6 nodes 10 elements
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay for Quads)
Info    : Done meshing 2D (Wall 0.000366734s, CPU 0.000367s)
Info    : 6 nodes 14 elements
Info    : Recombining 2D mesh...
Info    : Blossom: 3 internal 4 closed
Info    : Blossom recombination completed (Wall 6.9226e-05s, CPU 6.9e-05s): 2 quads, 0 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 1, min Q = 1
Info    : Done recombining 2D mesh (Wall 8.1765e-05s, CPU 8.5e-05s)
Info    : Meshing order 2 (curvilinear on)...
Info    : [  0%] Meshing curve 1 order 2
Info    : [ 20%] Meshing curve 2 order 2
Info    : [ 40%] Meshing curve 3 order 2
Info    : [ 60%] Meshing curve 4 order 2
Info    : [ 80%] Meshing surface 1 ord

In [4]:
# Néhány láthatósági beállítás 0:kikapcs. 1:bekapcs.
gmsh.option.setNumber("Geometry.CurveLabels", 0)
gmsh.option.setNumber("Mesh.Points", 0)
gmsh.option.setNumber("Mesh.Lines", 0)
gmsh.option.setNumber("Mesh.SurfaceEdges", 1)
gmsh.option.setNumber("Mesh.NodeLabels", 1)
gmsh.option.setNumber("Mesh.LineLabels", 0)
gmsh.option.setNumber("Mesh.SurfaceLabels", 0)

In [5]:
gmsh.option.setNumber("View.IntervalsType", 2)
gmsh.option.setNumber("View.VectorType", 2)
gmsh.option.setNumber("View.GlyphLocation", 2)

In [6]:
uvec = gmsh.view.add("u")
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
display(nodeTags)
uu = [1, 0, 0,
    1, 0, 0,
    1, 0, 0,
    1, 0, 0,
    1, 0, 0,
    0, 1, 0,
    0, 1, 0,
    0, 1, 0,
    1, 0, 0,
    0, 1, 0,
    0, 1, 0,
    0, 1, 0,
    0, 1, 0,
    0, 1, 0,
    0, 1, 0]
#nodeTags = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
gmsh.view.addHomogeneousModelData(uvec, 0, "rectangle", "NodeData", nodeTags, uu, 0, 3)
nodeTags

15-element Vector{UInt64}:
 0x0000000000000001
 0x0000000000000002
 0x0000000000000003
 0x0000000000000004
 0x0000000000000005
 0x0000000000000006
 0x0000000000000007
 0x0000000000000008
 0x0000000000000009
 0x000000000000000a
 0x000000000000000b
 0x000000000000000c
 0x000000000000000d
 0x000000000000000e
 0x000000000000000f

15-element Vector{UInt64}:
 0x0000000000000001
 0x0000000000000002
 0x0000000000000003
 0x0000000000000004
 0x0000000000000005
 0x0000000000000006
 0x0000000000000007
 0x0000000000000008
 0x0000000000000009
 0x000000000000000a
 0x000000000000000b
 0x000000000000000c
 0x000000000000000d
 0x000000000000000e
 0x000000000000000f

In [7]:
uvec = gmsh.view.add("v")
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
display(nodeTags)
uu = [[1.0, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [1, 0, 0],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 0]]
#nodeTags = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
gmsh.view.addModelData(uvec, 0, "rectangle", "NodeData", nodeTags, uu, 0, 3)
nodeTags

15-element Vector{UInt64}:
 0x0000000000000001
 0x0000000000000002
 0x0000000000000003
 0x0000000000000004
 0x0000000000000005
 0x0000000000000006
 0x0000000000000007
 0x0000000000000008
 0x0000000000000009
 0x000000000000000a
 0x000000000000000b
 0x000000000000000c
 0x000000000000000d
 0x000000000000000e
 0x000000000000000f

15-element Vector{UInt64}:
 0x0000000000000001
 0x0000000000000002
 0x0000000000000003
 0x0000000000000004
 0x0000000000000005
 0x0000000000000006
 0x0000000000000007
 0x0000000000000008
 0x0000000000000009
 0x000000000000000a
 0x000000000000000b
 0x000000000000000c
 0x000000000000000d
 0x000000000000000e
 0x000000000000000f

In [8]:
uvec = gmsh.view.add("σ")
elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(2, -1)
display(reshape(elemNodeTags[1], 9, :))
ss = [0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0]
#elemTags = [11, 12]
#elementNodeTags = [1, 2, 3, 4, 5, 6]
gmsh.view.addHomogeneousModelData(uvec, 0, "rectangle", "ElementNodeData", elemTags[1], ss, 0, 9)
display(elemTags)
#display(reshape(elemTags[1], 2, :))
display(reshape(elemNodeTags[1], 9, :))

gmsh.plugin.setNumber("Smooth", "View", 1)
gmsh.plugin.run("Smooth")

9×2 Matrix{UInt64}:
 0x0000000000000002  0x0000000000000001
 0x0000000000000003  0x0000000000000005
 0x0000000000000009  0x0000000000000009
 0x0000000000000005  0x0000000000000004
 0x0000000000000008  0x0000000000000006
 0x000000000000000a  0x000000000000000d
 0x000000000000000d  0x000000000000000b
 0x0000000000000007  0x000000000000000c
 0x000000000000000e  0x000000000000000f

1-element Vector{Vector{UInt64}}:
 [0x000000000000000b, 0x000000000000000c]

9×2 Matrix{UInt64}:
 0x0000000000000002  0x0000000000000001
 0x0000000000000003  0x0000000000000005
 0x0000000000000009  0x0000000000000009
 0x0000000000000005  0x0000000000000004
 0x0000000000000008  0x0000000000000006
 0x000000000000000a  0x000000000000000d
 0x000000000000000d  0x000000000000000b
 0x0000000000000007  0x000000000000000c
 0x000000000000000e  0x000000000000000f

Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)


2

In [9]:
T = gmsh.view.add("T")
elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(2, -1)
display(reshape(elemNodeTags[1], 9, :))
display(reshape(elemTags[1], 1, :))
TT = [[1, 0, 0, 0, 0, 0, 0, 0, 3],
    [0, 0, 0, 0, 0, 0, 0, 0, 3]]
#elemTags = [11, 12]
#elementNodeTags = [1, 2, 3, 4, 5, 6]
gmsh.view.addModelData(T, 0, "rectangle", "ElementNodeData", elemTags[1], TT, 0, 1)
#display(reshape(elemTags[1], 2, :))
display(reshape(elemNodeTags[1], 1, :))

gmsh.plugin.setNumber("Smooth", "View", -1)
gmsh.plugin.run("Smooth")

9×2 Matrix{UInt64}:
 0x0000000000000002  0x0000000000000001
 0x0000000000000003  0x0000000000000005
 0x0000000000000009  0x0000000000000009
 0x0000000000000005  0x0000000000000004
 0x0000000000000008  0x0000000000000006
 0x000000000000000a  0x000000000000000d
 0x000000000000000d  0x000000000000000b
 0x0000000000000007  0x000000000000000c
 0x000000000000000e  0x000000000000000f

1×2 Matrix{UInt64}:
 0x000000000000000b  0x000000000000000c

1×18 Matrix{UInt64}:
 0x0000000000000002  0x0000000000000003  …  0x000000000000000f

Info    : Running Plugin(Smooth)...
Info    : Done running Plugin(Smooth)


4

In [10]:
gmsh.view.probe(T, 0.5, 0.5, 0)

([3.0], 0.0)

In [11]:
#gmsh.write("rect.geo")
#gmsh.write("rect.msh")
#gmsh.write("rect.pos")

In [12]:
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.11.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 20221221
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] LinuxJoystick MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.14.4 (real arithmtic)
OCC version   : 7.6.1
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [13]:
gmsh.finalize()