In [27]:
import gmsh
gmsh.initialize()
using LinearAlgebra, SparseArrays
using Plots

In [28]:
# Adatok
E = 2e5
ν = 0.3
ρ = 7.85e-9

height = 10
base = 100
elemSize = 1

approxOrder = 1
internalNodes = 0
quadElements = 1

1

In [29]:
# Geometria megrajzolása
gmsh.model.add("rectangle")

p1 = gmsh.model.occ.addPoint(0, 0, 0)
p2 = gmsh.model.occ.addPoint(base, 0, 0)
p3 = gmsh.model.occ.addPoint(base, height, 0)
p4 = gmsh.model.occ.addPoint(0, height, 0)

l1 = gmsh.model.occ.addLine(p1, p2)
l2 = gmsh.model.occ.addLine(p2, p3)
l3 = gmsh.model.occ.addLine(p3, p4)
l4 = gmsh.model.occ.addLine(p4, p1)

cl1 = gmsh.model.occ.addCurveLoop([l1, l2, l3, l4])

sf1 = gmsh.model.occ.addPlaneSurface([cl1])

gmsh.model.occ.synchronize()

In [30]:
# Megfogások és terhelések helyének megadása
# az egyes peremfeltételek helyét megadó geometriai objektumokat
# csoportokba rendezzük

# merev fa az ütközés utáni pillanattól
supp = gmsh.model.addPhysicalGroup(1, [l2])
gmsh.model.setPhysicalName(1, supp, "FixRightX")

In [31]:
# Végeselemes felosztás elvégzése

# lekérjük az összes csomópontot
all = gmsh.model.getEntities(0)
# megadjuk, hogy a csomóponthoz rendelt eleméret mekkora legyen
gmsh.model.mesh.setSize(all, elemSize)
# kiválasztjuk a 8-as számú hálózó algoritmust a 2D-s sf1 felülethez
gmsh.model.mesh.setAlgorithm(2, sf1, 8)
# legeneráljuk a hálót a felület kontúrjához (1D-s)
gmsh.model.mesh.generate(1)
# legeneráljuk a hálót a felülethez (2D-s)
gmsh.model.mesh.generate(2)
# a legenerált háromszög elemeket négyszög elemekké alakítjuk
if quadElements == 1
    gmsh.model.mesh.recombine()
end
# másodfokú elemekhez:
# belső csomópontok használata
if internalNodes == 1
    gmsh.option.setNumber("Mesh.SecondOrderIncomplete", 0) # 0:belső csomópontokkal 1:csak éleken lévő csomópontokkal
else
    gmsh.option.setNumber("Mesh.SecondOrderIncomplete", 1) # 0:belső csomópontokkal 1:csak éleken lévő csomópontokkal
end
# közelítés fokszáma (1-től 5-ig)
gmsh.model.mesh.setOrder(approxOrder)

Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 30%] Meshing curve 2 (Line)
Info    : [ 50%] Meshing curve 3 (Line)
Info    : [ 80%] Meshing curve 4 (Line)
Info    : Done meshing 1D (Wall 0.000998256s, CPU 0s)
Info    : 220 nodes 224 elements
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay for Quads)
Info    : Done meshing 2D (Wall 0.224067s, CPU 0.173319s)
Info    : 1111 nodes 2224 elements
Info    : Recombining 2D mesh...
Info    : Blossom: 2890 internal 216 closed
Info    : Blossom recombination completed (Wall 0.0387019s, CPU 0.03542s): 1000 quads, 0 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 0.999062, min Q = 0.963526
Info    : Done recombining 2D mesh (Wall 0.0389848s, CPU 0.035699s)


In [32]:
# Néhány láthatósági beállítás 0:kikapcs. 1:bekapcs.
gmsh.option.setNumber("Geometry.CurveLabels", 0)
gmsh.option.setNumber("Mesh.Points", 0)
gmsh.option.setNumber("Mesh.Lines", 0)
gmsh.option.setNumber("Mesh.SurfaceEdges", 1)
gmsh.option.setNumber("Mesh.NodeLabels", 0)
gmsh.option.setNumber("Mesh.LineLabels", 0)
gmsh.option.setNumber("Mesh.SurfaceLabels", 0)

In [33]:
# Anyagállandók mátrixa SA feladathoz
D = E / ((1 + ν) * (1 - 2ν)) * [1-ν ν 0; ν 1-ν 0; 0 0 (1-2ν)/2]

3×3 Matrix{Float64}:
 2.69231e5  1.15385e5      0.0
 1.15385e5  2.69231e5      0.0
 0.0        0.0        76923.1

In [34]:
# Anyagállandók mátrixa ÁSF feladathoz
D = E / (1 - ν^2) * [1 ν 0; ν 1 0; 0 0 (1-ν)/2]

3×3 Matrix{Float64}:
     2.1978e5  65934.1           0.0
 65934.1           2.1978e5      0.0
     0.0           0.0       76923.1

In [35]:
# Merevségi mátrix felépítése
# csomópontok sorszámának lekérése
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
# végeselemek típusának, sorszámának és kapcsolati mátrixának (connectivity matrix) lekérése
elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(2, -1)
# a lefoglalandó memória méretének becslése
lengthOfIJV = sum([(div(length(elemNodeTags[i]), length(elemTags[i])) * 2)^2 * length(elemTags[i]) for i in 1:length(elemTags)])
nn = []
I = []
J = []
V = []
V = convert(Vector{Float64}, V)
sizehint!(I, lengthOfIJV)
sizehint!(J, lengthOfIJV)
sizehint!(V, lengthOfIJV)
for i in 1:length(elemTypes)
    et = elemTypes[i]
    elementName, dim, order, numNodes::Int64, localNodeCoord, numPrimaryNodes = gmsh.model.mesh.getElementProperties(et)
    intPoints, intWeights = gmsh.model.mesh.getIntegrationPoints(et, "Gauss" * string(2approxOrder))
    numIntPoints = length(intWeights)
    comp, dfun, ori = gmsh.model.mesh.getBasisFunctions(et, intPoints, "GradLagrange")
    ∇h = reshape(dfun, :, numIntPoints)
    nnet = zeros(Int, length(elemTags[i]), numNodes)
    invJac = zeros(3, 3numIntPoints)
    Iidx = zeros(Int, numNodes * 2, numNodes * 2)
    Jidx = zeros(Int, numNodes * 2, numNodes * 2)
    for k in 1:numNodes*2, l in 1:numNodes*2
        Iidx[k, l] = l
        Jidx[k, l] = k
    end
    ∂h = zeros(3, numNodes * numIntPoints) # ∂h-t mindig csak felül kellene írni, nem kell újra és újra memóriát foglalni neki.
    B = zeros(3 * numIntPoints, 2 * numNodes) # B-t mindig csak felül kellene írni?
    K1 = zeros(2 * numNodes, 2 * numNodes)
    nn2 = zeros(Int, 2 * numNodes)
    for j in 1:length(elemTags[i])
        elem = elemTags[i][j]
        for k in 1:numNodes
            nnet[j, k] = elemNodeTags[i][(j-1)*numNodes+k]
        end
        jac, jacDet, coord = gmsh.model.mesh.getJacobian(elem, intPoints)
        Jac = reshape(jac, 3, :)
        for k in 1:numIntPoints
            invJac[1:3, 3*k-2:3*k] = inv(Jac[1:3, 3*k-2:3*k])'
        end
        ∂h *= 0
        for k in 1:numIntPoints, l in 1:numNodes
            ∂h[1:2, (k-1)*numNodes+l] = invJac[1:2, k*3-2:k*3-1] * ∇h[l*3-2:l*3-1, k] #??????????????????
        end
        B *= 0
        for k in 1:numIntPoints, l in 1:numNodes
            B[k*3-0, l*2-0] = B[k*3-2, l*2-1] = ∂h[1, (k-1)*numNodes+l]
            B[k*3-0, l*2-1] = B[k*3-1, l*2-0] = ∂h[2, (k-1)*numNodes+l]
        end
        K1 *= 0
        for k in 1:numIntPoints
            B1 = B[k*3-2:k*3, 1:2*numNodes]
            K1 += B1' * D * B1 * jacDet[k] * intWeights[k]
        end
        nn2[1:2:2*numNodes] = 2 * nnet[j, 1:numNodes] .- 1
        nn2[2:2:2*numNodes] = 2 * nnet[j, 1:numNodes]
        append!(I, nn2[Iidx[:]])
        append!(J, nn2[Jidx[:]])
        append!(V, K1[:])
    end
    push!(nn, nnet)
end
K = sparse(I, J, V)
K0 = copy(K)
display(K)

2222×2222 SparseMatrixCSC{Float64, Int64} with 37324 stored entries:
⎡⠻⣦⡀⠀⠃⠀⠀⠐⡆⠘⣇⠀⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠈⠻⣦⡀⠀⠀⠀⢳⠀⢹⡀⠈⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠉⠀⠀⠈⠻⣦⡀⠀⠘⡎⠉⡇⡀⠈⢧⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⢀⠀⠀⠀⠀⠈⠻⣦⡀⢳⡀⢹⠁⠀⠈⢧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⣈⠉⠙⠒⡲⠤⢤⣈⠑⣤⡁⣾⡏⠓⡦⣬⠻⣬⣛⡢⡂⢈⢸⢤⡠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠉⠙⠓⠲⠧⠤⣄⣈⣡⣬⡻⣮⡝⠲⣥⣸⠻⡉⢙⣦⡇⡘⡮⣄⣰⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠉⠓⠦⣄⡀⠈⠁⠀⢯⠉⢳⡉⠻⢆⠉⠸⣮⠹⡽⡍⠅⠹⣎⠀⠩⠀⠁⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠉⢓⠦⣄⡈⣯⣁⣻⣃⡀⠑⢄⢘⣆⣉⠹⣇⣀⠋⢧⣀⠀⡀⠀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⡛⣦⡟⠢⣎⡛⠲⢴⣑⢜⣧⠢⣞⣯⢳⠦⣟⠦⣂⡶⠎⡇⠲⠄⠠⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠻⡸⠳⣴⡗⠯⣇⡘⠩⡛⠿⣧⡫⡽⣾⣀⢻⠀⡺⣥⡶⢧⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⡈⢈⣉⠩⣅⡁⠉⢹⡾⣽⣏⡮⣿⣿⣾⠍⡿⠘⣆⡧⣳⣿⡌⠳⢾⠀⠄⠴⡆⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠒⣖⠊⢯⠊⠙⠯⣄⠹⡖⠚⢻⡞⠟⠑⢄⠒⣆⠊⠿⡏⠳⢦⡀⠰⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠊⠐⠚⠃⠂⠀⠘⠻⡝⠛⠒⣛⠋⠸⢤⣑⢜⠛⡲⣅⢳⢦⣙⡸⣴⣄⠙⢦⢤⣀⡄⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⡅⠀⠀⠈⢨⡼⠞⣮⠬⡽⣮⡄⢻⡠⠵⣧⡿⢭⣄⠻⢯⢀⡍⠳⣍⡀⠉⠅⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⠮⠥⠼⣏⣽⣾⢯⡉⢥⣙⡟⣏⡿⣯⣌⠙⢮⢀⣁⣿⣭⢉⣀⣄⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⠆⠀⠙⢦⡉⠈⠳⣌⢳⣤⡙⣆⠙⠛⢄⠨⠿⣧⣤⢿⢳⡤⣄⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠂⠀⠀⠚⠓⠐⠂⢒⣮⠋⢓⠊⢓⣦⡆⢱⣶⣼⡟⣲⣴⣿⣿⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡅⠀⠀⣄⠙⢧⡉⣥⣼⠉⣿⣶⠿⣛⣼⣾⢻⣿⣏⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠀⠀⠈⣗⠃⠹⡇⢛⢿⣓⢘⣾⣾⣛⣻⣾⣾⡿⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠼⠇⠄⠀⢼⠀⢯⣿⣿⡿⢿⣾⡿⣿⣿⎦

In [36]:
# Tömeg mátrix felépítése
# csomópontok sorszámának lekérése
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
# végeselemek típusának, sorszámának és kapcsolati mátrixának (connectivity matrix) lekérése
elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(2, -1)
# a lefoglalandó memória méretének becslése
lengthOfIJV = sum([(div(length(elemNodeTags[i]), length(elemTags[i])) * 2)^2 * length(elemTags[i]) for i in 1:length(elemTags)])
nn = []
I = []
J = []
V = [] # Ezt vajon nem kellene átnevezni másnak? Ebben voltak a K elemei is... A 'sparse' parancs készített róla másolatot?
V = convert(Vector{Float64}, V)
sizehint!(I, lengthOfIJV)
sizehint!(J, lengthOfIJV)
sizehint!(V, lengthOfIJV)
for i in 1:length(elemTypes)
    et = elemTypes[i]
    elementName, dim, order, numNodes::Int64, localNodeCoord, numPrimaryNodes = gmsh.model.mesh.getElementProperties(et)
    intPoints, intWeights = gmsh.model.mesh.getIntegrationPoints(et, "Gauss" * string(2approxOrder))
    numIntPoints = length(intWeights)
    comp, fun, ori = gmsh.model.mesh.getBasisFunctions(et, intPoints, "Lagrange")
    h = reshape(fun, :, numIntPoints)
    nnet = zeros(Int, length(elemTags[i]), numNodes)
    Iidx = zeros(Int, numNodes * 2, numNodes * 2)
    Jidx = zeros(Int, numNodes * 2, numNodes * 2)
    for k in 1:numNodes*2, l in 1:numNodes*2
        Iidx[k, l] = l
        Jidx[k, l] = k
    end
    nn2 = zeros(Int, 2 * numNodes)
    H = zeros(2 * numIntPoints, 2 * numNodes)
    for k in 1:numIntPoints, l in 1:numNodes
        H[k*2-1, l*2-1] = H[k*2-0, l*2-0] = h[(k-1)*numNodes+l]
    end
    M1 = zeros(2 * numNodes, 2 * numNodes)
    for j in 1:length(elemTags[i])
        elem = elemTags[i][j]
        for k in 1:numNodes
            nnet[j, k] = elemNodeTags[i][(j-1)*numNodes+k]
        end
        jac, jacDet, coord = gmsh.model.mesh.getJacobian(elem, intPoints)
        M1 *= 0
        for k in 1:numIntPoints
            H1 = H[k*2-1:k*2, 1:2*numNodes]
            M1 += H1' * H1 * jacDet[k] * intWeights[k]
        end
        M1 *= ρ
        nn2[1:2:2*numNodes] = 2 * nnet[j, 1:numNodes] .- 1
        nn2[2:2:2*numNodes] = 2 * nnet[j, 1:numNodes]
        append!(I, nn2[Iidx[:]])
        append!(J, nn2[Jidx[:]])
        append!(V, M1[:])
    end
    push!(nn, nnet)
end
M = sparse(I, J, V)
M = spdiagm(vec(sum(M, dims=2))) # lumped mass matrix
M0 = copy(M)
display(M)

2222×2222 SparseMatrixCSC{Float64, Int64} with 2222 stored entries:
⎡⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⎦

In [37]:
#using SymRCM
using Arpack
#perm = symrcm(K)
#Kp = K[perm, perm]
#Mp = M[perm, perm]
#ω², ϕ = Arpack.eigs(Kp, Mp; nev=1, which=:LM)
ω², ϕ = Arpack.eigs(K, M; nev=1, which=:LM)

#if norm(Kp * ϕ - λ²[1] * Mp * ϕ) > 1e-6
if norm(K * ϕ - ω²[1] * M * ϕ) > 1e-6
    error("Túl nagy a hiba a legnagyobb sajátérték számításánál")
end
display(real(ω²))

1-element Vector{Float64}:
 1.1346033680329055e14

In [38]:
# Teher vektor felépítése
p = [0, 1]
dof, dof = size(K)
f = zeros(dof)
#tags = gmsh.model.getEntitiesForPhysicalGroup(1, trac1)
tags = []
for i ∈ 1:length(tags)
    elementTypes, elementTags, elemNodeTags = gmsh.model.mesh.getElements(1, tags[i])
    if length(elementTypes) != 1
        error("A peremen nem csak egyfajta végeselem van!")
    end
    #elements = elementTags[1]
    elementName, dim, order, numNodes::Int64, localNodeCoord, numPrimaryNodes = gmsh.model.mesh.getElementProperties(elementTypes[1])
    nnoe = reshape(elemNodeTags[1], numNodes, :)'
    intPoints, intWeights = gmsh.model.mesh.getIntegrationPoints(elementTypes[1], "Gauss" * string(approxOrder))
    numIntPoints = length(intWeights)
    comp, fun, ori = gmsh.model.mesh.getBasisFunctions(elementTypes[1], intPoints, "Lagrange")
    h = reshape(fun, :, numIntPoints)
    comp, dfun, ori = gmsh.model.mesh.getBasisFunctions(elementTypes[1], intPoints, "GradLagrange")
    ∇h = reshape(dfun, :, numIntPoints)
    H = zeros(2 * numIntPoints, 2 * numNodes)
    for j in 1:numIntPoints
        for k in 1:numNodes
            H[j*2-1, k*2-1] = h[k, j]
            H[j*2-0, k*2-0] = h[k, j]
        end
    end
    f1 = zeros(2 * numNodes)
    nn2 = zeros(Int, 2 * numNodes)
    for l in 1:length(elementTags[1])
        elem = elementTags[1][l]
        jac, jacDet, coord = gmsh.model.mesh.getJacobian(elem, intPoints)
        Jac = reshape(jac, 3, :)
        f1 *= 0
        for j in 1:numIntPoints
            H1 = H[j*2-1:j*2, 1:2*numNodes]
            Ja = √((Jac[1, 3*j-2])^2 + (Jac[2, 3*j-2])^2)
            f1 += H1' * p * Ja * intWeights[j]
        end
        nn2[1:2:2*numNodes] = 2 * nnoe[l, 1:numNodes] .- 1
        nn2[2:2:2*numNodes] = 2 * nnoe[l, 1:numNodes]
        f[nn2] += f1
    end
end
display(f)

2222-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

$$\mathbf{M}\ddot{\mathbf{q}}+\mathbf{K}\mathbf{q}=\mathbf{f}$$
$$\mathbf{M}\ddot{\mathbf{q}}_n+\mathbf{K}\mathbf{q}_n=\mathbf{f}_n$$
$$\ddot{\mathbf{q}}_n = \frac{\mathbf{q}_{n+1}-2\mathbf{q}_{n}+\mathbf{q}_{n-1}}{\Delta t^2}$$
$$\mathbf{M}\mathbf{q}_{n+1}=\left(2\mathbf{M}-\Delta t^{2}\mathbf{K}\right)\mathbf{q}_{n}-\mathbf{M}\mathbf{q}_{n-1}+\Delta t^{2}\mathbf{f}_{n}$$

In [39]:
nodeTags, coord = gmsh.model.mesh.getNodesForPhysicalGroup(1, supp)
nodeTags *= 2
nodeTags .-= 1 # x irányú megfogás
for i ∈ nodeTags
    K[i, :] .= 0
    K[:, i] .= 0
    K[i, i] = 1
    M[i, :] .= 0
    M[:, i] .= 0
    M[i, i] = 1
    f[i] = 0
end
dropzeros!(K)
dropzeros!(M)

2222×2222 SparseMatrixCSC{Float64, Int64} with 2222 stored entries:
⎡⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎤
⎢⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⎥
⎢⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⠀⠀⎥
⎣⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠑⢄⎦

$$\mathbf{q}\left(t+\Delta t\right)=\mathbf{q}\left(t\right)+\dot{\mathbf{q}}\left(t\right)\Delta t+\ddot{\mathbf{q}}\left(t\right)\frac{\Delta t^{2}}{2}$$
Ha $t=0$ és $\Delta t$ helyére $-\Delta t$-t írunk
$$\mathbf{q}\left(-\Delta t\right)=\mathbf{q}\left(0\right)-\dot{\mathbf{q}}\left(0\right)\Delta t+\ddot{\mathbf{q}}\left(0\right)\frac{\Delta t^{2}}{2}$$
vagyis
$$\mathbf{q}_{-1}=\mathbf{q}_{0}-\dot{\mathbf{q}}_{0}\Delta t+\ddot{\mathbf{q}}_{0}\frac{\Delta t^{2}}{2}$$
ahol
$$\ddot{\mathbf{q}}_{0}=\mathbf{M}^{-1}\left(\mathbf{f}_{0}-\mathbf{K}\mathbf{q}_{0}\right)$$

In [40]:
ωₘₐₓ = √real(ω²[1])
Tₘᵢₙ = 2π / ωₘₐₓ
Δt = Tₘᵢₙ / π # * (√(1 + ξₘₐₓ^2) - ξₘₐₓ)

1.8776211190148834e-7

In [41]:
initVelocity = 1000

u0 = zeros(dof)
v0 = zeros(dof)
v0[1:2:dof] .= initVelocity

nodeTags, coord = gmsh.model.mesh.getNodesForPhysicalGroup(1, supp)
nodeTags *= 2
nodeTags .-= 1
v0[nodeTags] .= 0

a0 = M \ (f - K * u0)
u00 = u0 - v0 * Δt + a0 * Δt^2 / 2

2222-element Vector{Float64}:
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  0.0
  ⋮
  0.0
 -0.00018776211190148833
  0.0
 -0.00018776211190148833
  0.0
 -0.00018776211190148833
  0.0
 -0.00018776211190148833
  0.0

In [42]:
invM = spdiagm(1 ./ diag(M))
nsteps = 200 # ceil(Int64, Tmax / Δt)

u = zeros(dof, nsteps)
v = zeros(dof, nsteps)
#p = zeros(nsteps)
t = zeros(nsteps)
kene = zeros(nsteps)
sene = zeros(nsteps)
diss = zeros(nsteps)

u[:, 1] = u0
v[:, 1] = v0
t[1] = 0
kene[1] = dot(v0' * M, v0) / 2
sene[1] = dot(u0' * K, u0) / 2

for i in 2:nsteps
    u1 = 2.0 * u0 - u00 + Δt * Δt * invM * (f - K * u0)
    u[:, i] = u1
    v1 = (u1 - u0) / Δt
    v[:, i] = v1
    t[i] = t[i-1] + Δt
    kene[i] = dot(v1' * M, v1) / 2
    sene[i] = dot(u1' * K, u1) / 2
    #diss[i] = dot(v1' * C, v1)
    u00 = u0
    u0 = u1
end

kene

200-element Vector{Float64}:
 3.9053750000000442
 3.905375000000044
 3.8671640520549557
 3.8292240225851457
 3.7918676440636694
 3.7555484261670995
 3.71967141449822
 3.6837782939176695
 3.6478563052702673
 3.6108297624551877
 ⋮
 3.1615481994719015
 3.1993979961939347
 3.2357423332274875
 3.2699910105362764
 3.3047451401625643
 3.342698550547178
 3.3798898313219126
 3.418933290767951
 3.457588910581911

In [43]:
gmsh.option.setNumber("View.IntervalsType", 2)
gmsh.option.setNumber("View.VectorType", 2)

In [44]:
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
non = length(nodeTags)
uvec = gmsh.view.add("uvec")
uu = zeros(3 * non)
for j in 1:nsteps
    for i in 1:length(nodeTags)
        uu[3i-2] = u[2*nodeTags[i]-1, j]
        uu[3i-1] = u[2*nodeTags[i]-0, j]
    end
    gmsh.view.addHomogeneousModelData(uvec, j - 1, "rectangle", "NodeData", nodeTags, uu, t[j], 3)
end

In [45]:
gmsh.option.setNumber("View.IntervalsType", 3)
gmsh.option.setNumber("View.VectorType", 2)

In [46]:
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
non = length(nodeTags)
vvec = gmsh.view.add("vvec")
vv = zeros(3 * non)
for j in 1:nsteps
    for i in 1:length(nodeTags)
        vv[3i-2] = v[2*nodeTags[i]-1, j]
        vv[3i-1] = v[2*nodeTags[i]-0, j]
    end
    gmsh.view.addHomogeneousModelData(vvec, j - 1, "rectangle", "NodeData", nodeTags, vv, t[j], 3)
end

In [47]:
#gmsh.write("rect.geo")
#gmsh.write("rect.msh")
#gmsh.write("rect.pos")

In [48]:
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.11.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 20221221
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] LinuxJoystick MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.14.4 (real arithmtic)
OCC version   : 7.6.1
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [49]:
gmsh.finalize()