In [29]:
import gmsh
gmsh.initialize()

In [30]:
# Data
l = 100
b = 10
es = 2

2

In [31]:
gmsh.model.add("rectangle")

p1 = gmsh.model.occ.addPoint(0, 0, 0)
p2 = gmsh.model.occ.addPoint(100, 0, 0)
p3 = gmsh.model.occ.addPoint(100, 200, 0)
p4 = gmsh.model.occ.addPoint(0, 200, 0)

l1 = gmsh.model.occ.addLine(p1, p2)
l2 = gmsh.model.occ.addLine(p2, p3)
l3 = gmsh.model.occ.addLine(p3, p4)
l4 = gmsh.model.occ.addLine(p4, p1)

cl1 = gmsh.model.occ.addCurveLoop([l1, l2, l3, l4])

sf1 = gmsh.model.occ.addPlaneSurface([cl1])

gmsh.model.occ.synchronize()

In [32]:
all = gmsh.model.getEntities(0);
gmsh.model.mesh.setSize(all, 25) # element size
gmsh.model.mesh.setAlgorithm(2, sf1, 8)
gmsh.model.mesh.generate(1)
gmsh.model.mesh.generate(2)
gmsh.model.mesh.recombine()
# másodfokú elemekhez:
#gmsh.option.setNumber("Mesh.SecondOrderIncomplete", 1)
#gmsh.model.mesh.setOrder(2)

gmsh.option.setNumber("Mesh.Points", 1)

Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 30%] Meshing curve 2 (Line)
Info    : [ 50%] Meshing curve 3 (Line)
Info    : [ 80%] Meshing curve 4 (Line)
Info    : Done meshing 1D (Wall 0.0130298s, CPU 0.002876s)
Info    : 24 nodes 28 elements
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay for Quads)
Info    : Done meshing 2D (Wall 0.0805975s, CPU 0.032784s)
Info    : 45 nodes 92 elements
Info    : Recombining 2D mesh...
Info    : Blossom: 84 internal 21 closed
Info    : Blossom recombination completed (Wall 0.014922s, CPU 0.006664s): 32 quads, 0 triangles, 0 invalid quads, 0 quads with Q < 0.1, avg Q = 1, min Q = 1
Info    : Done recombining 2D mesh (Wall 0.0150541s, CPU 0.006762s)


In [33]:
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)

(UInt64[0x0000000000000001, 0x0000000000000002, 0x0000000000000003, 0x0000000000000004, 0x0000000000000005, 0x0000000000000006, 0x0000000000000007, 0x0000000000000008, 0x0000000000000009, 0x000000000000000a  …  0x0000000000000024, 0x0000000000000025, 0x0000000000000026, 0x0000000000000027, 0x0000000000000028, 0x0000000000000029, 0x000000000000002a, 0x000000000000002b, 0x000000000000002c, 0x000000000000002d], [0.0, 0.0, 0.0, 100.0, 0.0, 0.0, 100.0, 200.0, 0.0, 0.0  …  0.0, 50.0, 150.0, 0.0, 50.0, 125.0, 0.0, 50.0, 75.0, 0.0], Float64[])

In [34]:
gmsh.model.mesh.getElement(1)

(15, UInt64[0x0000000000000001], 0, 1)

In [35]:
gmsh.model.mesh.getElementTypes()

3-element Vector{Int32}:
  1
  3
 15

In [36]:
entities = gmsh.model.getEntities(2)
nodeTags, nodeCoords, nodeParams = gmsh.model.mesh.getNodes(-1, -1)
elemTypes, elemTags, elemNodeTags = gmsh.model.mesh.getElements(2, -1)
#println(Int64.(elemNodeTags[1]))
#display(nodeCoords)
xynodes = reshape(nodeCoords, 3, :)
display(xynodes)
connectivity = (Int64.(reshape(elemNodeTags[1], 4, :)))'
display(connectivity)

3×45 Matrix{Float64}:
 0.0  100.0  100.0    0.0  25.0  50.0  …  50.0   50.0   50.0   50.0  50.0
 0.0    0.0  200.0  200.0   0.0   0.0     50.0  100.0  150.0  125.0  75.0
 0.0    0.0    0.0    0.0   0.0   0.0      0.0    0.0    0.0    0.0   0.0

32×4 adjoint(::Matrix{Int64}) with eltype Int64:
 27  43  39  36
  1   5  33  24
  2   8  34   7
 11  12  38  26
  3  15  35  14
 24  33  40  23
 28  44  43  27
 40  41  45  30
 29  30  45  42
 17   4  18  36
  ⋮          
 30  22  23  40
 34  25  41  31
 42  45  37  26
 44  28  29  42
 38  32  43  44
 31  41  40  33
 32  35  39  43
 25  37  45  41
 26  38  44  42

In [37]:
et = gmsh.model.mesh.getElementsByType(3)
convert.(Int64, et[1])'

1×32 adjoint(::Vector{Int64}) with eltype Int64:
 29  30  31  32  33  34  35  36  37  …  52  53  54  55  56  57  58  59  60

In [38]:
xx, ww = gmsh.model.mesh.getIntegrationPoints(3, "Gauss3")
display(reshape(xx, 3, :))
display(ww)

3×4 Matrix{Float64}:
 -0.57735  -0.57735   0.57735  0.57735
 -0.57735   0.57735  -0.57735  0.57735
  0.0       0.0       0.0      0.0

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [39]:
xx0 = [-1, -1, 0, 1, -1, 0, 1, 1, 0, -1, 1, 0]

12-element Vector{Int64}:
 -1
 -1
  0
  1
 -1
  0
  1
  1
  0
 -1
  1
  0

In [40]:
comp, fun, ori = gmsh.model.mesh.getBasisFunctions(3, xx0, "Lagrange1")
display(comp)
display(reshape(fun, 4, :))
display(ori)

1

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

1

In [41]:
comp, fun, ori = gmsh.model.mesh.getBasisFunctions(3, xx0, "GradLagrange1")
display(comp)
display(reshape(fun, :, 4))
display(ori)

3

12×4 Matrix{Float64}:
 -0.5  -0.5   0.0   0.0
 -0.5   0.0   0.0  -0.5
  0.0   0.0   0.0   0.0
  0.5   0.5   0.0   0.0
  0.0  -0.5  -0.5   0.0
  0.0   0.0   0.0   0.0
  0.0   0.0   0.5   0.5
  0.0   0.5   0.5   0.0
  0.0   0.0   0.0   0.0
  0.0   0.0  -0.5  -0.5
  0.5   0.0   0.0   0.5
  0.0   0.0   0.0   0.0

1

In [45]:
jac, det, coord = gmsh.model.mesh.getJacobian(30, xx0)
display(reshape(jac, 3, :)')
display(det)
display(reshape(coord, 3, :))

12×3 adjoint(::Matrix{Float64}) with eltype Float64:
 12.5   0.0  0.0
  0.0  12.5  0.0
  0.0   0.0  1.0
 12.5   0.0  0.0
  0.0  12.5  0.0
  0.0   0.0  1.0
 12.5   0.0  0.0
  0.0  12.5  0.0
  0.0   0.0  1.0
 12.5   0.0  0.0
  0.0  12.5  0.0
  0.0   0.0  1.0

4-element Vector{Float64}:
 156.25
 156.25
 156.25
 156.25

3×4 Matrix{Float64}:
 0.0  25.0  25.0   0.0
 0.0   0.0  25.0  25.0
 0.0   0.0   0.0   0.0

In [46]:
jac, det, coord = gmsh.model.mesh.getJacobians(3, xx0)
display(reshape(jac, 3, :)')
display(det)
display(reshape(coord, 3, :))

384×3 adjoint(::Matrix{Float64}) with eltype Float64:
  12.5   0.0  0.0
   0.0  12.5  0.0
   0.0   0.0  1.0
  12.5   0.0  0.0
   0.0  12.5  0.0
   0.0   0.0  1.0
  12.5   0.0  0.0
   0.0  12.5  0.0
   0.0   0.0  1.0
  12.5   0.0  0.0
   ⋮          
   0.0  12.5  0.0
 -12.5   0.0  0.0
   0.0  -0.0  1.0
   0.0  12.5  0.0
 -12.5   0.0  0.0
   0.0  -0.0  1.0
   0.0  12.5  0.0
 -12.5   0.0  0.0
   0.0  -0.0  1.0

128-element Vector{Float64}:
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
   ⋮
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25
 156.25

3×128 Matrix{Float64}:
  25.0   50.0   50.0   25.0  0.0  25.0  …  50.0   75.0   75.0   50.0   50.0
 150.0  150.0  175.0  175.0  0.0   0.0     50.0  100.0  125.0  125.0  100.0
   0.0    0.0    0.0    0.0  0.0   0.0      0.0    0.0    0.0    0.0    0.0

In [43]:
gmsh.fltk.run()
#gmsh.finalize()

-------------------------------------------------------
Version       : 4.11.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 20221221
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] LinuxJoystick MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.14.4 (real arithmtic)
OCC version   : 7.6.1
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------
