In [1]:
import gmsh
gmsh.initialize()
using LinearAlgebra, SparseArrays

In [2]:
gmsh.model.add("rectangle")

p1 = gmsh.model.occ.addPoint(0, 0, 0)
p2 = gmsh.model.occ.addPoint(-3, 4, 0)

l1 = gmsh.model.occ.addLine(p1, p2)

gmsh.model.occ.synchronize()

In [3]:
all = gmsh.model.getEntities(0)
gmsh.model.mesh.setSize(all, 2.5)  # element size
#gmsh.model.mesh.setAlgorithm(2, sf1, 8)
gmsh.model.mesh.generate(1)

gmsh.option.setNumber("Geometry.CurveLabels", 1)
gmsh.option.setNumber("Mesh.Points", 1)
gmsh.option.setNumber("Mesh.Lines", 1)
gmsh.option.setNumber("Mesh.NodeLabels", 1)
gmsh.option.setNumber("Mesh.LineLabels", 1)

Info    : Meshing 1D...
Info    : Meshing curve 1 (Line)
Info    : Done meshing 1D (Wall 0.000164667s, CPU 0.000143s)
Info    : 3 nodes 4 elements


In [4]:
dimTags = gmsh.model.getEntities(1)
elementTypes, elementTags, nodeTags = gmsh.model.mesh.getElements(dimTags[1][1], dimTags[1][1])
elementName, dim, order, numNodes::Int64, localNodeCoord, numPrimaryNodes = gmsh.model.mesh.getElementProperties(elementTypes[1])
intPoints, intWeights = gmsh.model.mesh.getIntegrationPoints(elementTypes[1], "Gauss3")
display(elementTags[1][1])
jac, jacDet, coord = gmsh.model.mesh.getJacobian(elementTags[1][1], intPoints)
Jac = reshape(jac, 3, :)
display(√(Jac[1, 1]^2 + Jac[2, 1]^2) * 2)
nn = zeros(Int, 2)
nn = ((reshape(nodeTags[1], numNodes, :))[1:2, 1])'
display(nn)
display(elementTags)
display(nodeTags)
display(numNodes)
reshape(nodeTags[1], numNodes, :)

0x0000000000000003

2.5

1×2 adjoint(::Vector{UInt64}) with eltype UInt64:
 0x0000000000000001  0x0000000000000003

1-element Vector{Vector{UInt64}}:
 [0x0000000000000003, 0x0000000000000004]

1-element Vector{Vector{UInt64}}:
 [0x0000000000000001, 0x0000000000000003, 0x0000000000000003, 0x0000000000000002]

2

2×2 Matrix{UInt64}:
 0x0000000000000001  0x0000000000000003
 0x0000000000000003  0x0000000000000002

In [5]:
gmsh.fltk.run()

-------------------------------------------------------
Version       : 4.11.1
License       : GNU General Public License
Build OS      : Linux64-sdk
Build date    : 20221221
Build host    : gmsh.info
Build options : 64Bit ALGLIB[contrib] ANN[contrib] Bamg Blas[petsc] Blossom Cgns DIntegration Dlopen DomHex Eigen[contrib] Fltk Gmm[contrib] Hxt Jpeg Kbipack Lapack[petsc] LinuxJoystick MathEx[contrib] Med Mesh Metis[contrib] Mmg Mpeg Netgen ONELAB ONELABMetamodel OpenCASCADE OpenCASCADE-CAF OpenGL OpenMP OptHom PETSc Parser Plugins Png Post QuadMeshingTools QuadTri Solver TetGen/BR Voro++[contrib] WinslowUntangler Zlib
FLTK version  : 1.4.0
PETSc version : 3.14.4 (real arithmtic)
OCC version   : 7.6.1
MED version   : 4.1.0
Packaged by   : geuzaine
Web site      : https://gmsh.info
Issue tracker : https://gitlab.onelab.info/gmsh/gmsh/issues
-------------------------------------------------------


In [6]:
gmsh.finalize()